### ISSUE TITLE
Is it possible to authenticate to Github to allow access to links to private Github repositories?

### ISSUE THREAD

**Issue by ramsesk** [AlexanderDokuchaev/md-dead-link-check#28]
My issue is, that my markdown files sometimes link to other private Github repositories. Currently, the Github Actions runners do not have access to private github repositories.

If it is already possible it would be nice to be able to read in the documentation (README.md) how to do that.
If it is not yet possible, it would be nice if we could perhaps use a Github PAT or `secrets.GITHUB_TOKEN` to authenticate requrests to `github.com/PrivateOrg/*`

**Comment by AlexanderDokuchaev** [comment]
Hi @ramsesk  
Now there is no way to use authiphication for request.
I see several problems with using github secrets:
- pull_request actions has no access to any secrets. In with case it will works only for push or scheduled actions
- need to set for which links will used token
- need to be more careful to avoid issue like https://github.com/AlexanderDokuchaev/md-dead-link-check/issues/21

For local run it's not problem to implement it, but need to some time to check all protentional security issues for github action.

**Comment by ramsesk** [comment]
Thanks for your reply @AlexanderDokuchaev . 

I haven't dived deep enough into your code to know about the intricacies. But I can definitely understand if this is not a trivial request. 

Currently, I've set it up to exclude some links via:

`pyproject.toml`:

```toml
[tool.md_dead_link_check]
# As long as we can't authenticate the Github requests, we need to disable checking these.
exclude_links = ["https://github.com/PrivateOrg/*"]
```
